### ISSUE TITLE
Songs being loaded multiple times and out of order when scrolling through larger playlists

### ISSUE THREAD

**Issue by suchasaltylemon** [jeffvli/feishin#53] opened 2023-03-15 14:57 UTC
## Expected Behavior
When scrolling through a playlist, songs which haven't been loaded in the view should be loaded in order with only one of each song

## Current Behavior
When scrolling through a playlist, the songs are being loaded multiple times and the track numbers are out of order. After it loads more tracks for the second time, they begin to form "clumps" of songs, starting in groups of 3.

## Steps to Reproduce
1. Go to playlist large enough to warrant more songs to be loaded

2. Scroll through playlist

https://user-images.githubusercontent.com/46686300/225348441-e904c0cb-4c4e-45cb-8ffa-52babac981ce.mp4

## Your Environment

- Operating System and version  **Windows 10 19045.2604**
- Feishin version **[0.0.1-alpha5](https://github.com/jeffvli/feishin/releases/tag/v0.0.1-alpha5)**

**Comment by kgarner7** [comment] 2024-01-23 05:09
Is this still an issue that you are seeing with latest?

**Comment by kgarner7** [comment] 2024-03-31 01:33
@suchasaltylemon @YourSandwich is this still an issue you are seeing in 0.6.1

**Comment by YourSandwich** [comment] 2024-03-31 08:13
@kgarner7 Not the songs anymore but my Playlists are duplicated now instead:
![image](https://github.com/jeffvli/feishin/assets/20018243/c8eb9af1-6c80-4e38-85ac-38e42a659b38)

And clearing the cache + relogin did not help.

**Comment by kgarner7** [comment] 2024-04-02 15:29
Since the new issue was resolved, I'll ask here again; is the song duplication/out of order still seen here?

**Comment by YourSandwich** [comment] 2024-04-02 15:36
The issue is not present anymore. At least for a Playlist with 91 entries.

**Comment by kgarner7** [comment] 2024-04-02 15:48
Thanks. I'll see if I can also not reproduce this using a large playlist, and I'll also wait a few more days for the suchasaltylemon. If I cannot reproduce and suchasaltylemon cannot either (or doesn't respond), I'll go ahead and close this.

**Comment by kgarner7** [comment] 2024-04-05 05:51
Since I haven't heard any updates here, I'll mark this issue as resolved. If that turns out not to be the case, please feel free to reopen this issue!

**Closed as completed by kgarner7** 2024-04-05 05:51 UTC
Labels: bug, frozen-due-to-age
