### ISSUE TITLE
[UI] Mobile Responsive Layout

### ISSUE THREAD

**Issue by rairulyle** [jeffvli/feishin#448] opened 2024-01-15 15:02 UTC
## What do you want to be added?

I have been using your docker build and accessing the web app on my tablet. However, I also want to access it via mobile, but the problem is that it doesn't look responsive and UI is out of place. I know that this may be a low prio but I want you to know that once this has been solved, I'll be one of the users who will uninstall mobile app jellyfin client!

**Comment by kgarner7** [comment] 2024-04-02 05:56
Duplicate of #33

**Closed as not planned by kgarner7** 2024-04-02 05:56 UTC
Labels: enhancement, frozen-due-to-age
