### ISSUE TITLE
Session is expired when alt tabbing

### ISSUE THREAD

**Issue by pokemonrocks9** [jeffvli/feishin#214] opened 2023-08-11 21:01 UTC
## Expected Behavior

Feishin open and use the server
## Current Behavior
Feishin will open for a short period of time then when alt tabbing suddenly closes the server and says session is expired. Server is a Jellyfin. 

Server crash in Feishin

Unable to atm

## Steps to Reproduce
Open Feishin, sign in, alt tab.

Unfortunately cannot yet

1.

2.

3.

4.

## Your Environment

-   Application version (e.g. v0.1.0) :0.3.0
-   Operating System and version (e.g. Windows 10) : Windows 11
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin 10.8.10
-   Node version (if developing locally) :
-Extra information: this bug report is on behalf of a friend who's struggling to get the app to run properly. I'm making this at work and can provide more information later.

**Comment by jeffvli** [comment] 2023-08-12 03:47
I don't think the issue is related to alt tabbing, my thoughts are that it's a permissions related issue that I'm unaware about on Jellyfin.

Is the person Feishin accessing your server on an account with limited permissions to your server?

**Comment by pokemonrocks9** [comment] 2023-08-12 04:02
To my knowledge they have the same permission as most on the server and
it's only them with the issue.

**Comment by jeffvli** [comment] 2023-08-12 04:54
Feishin logs you out if you get a `HTTP 401` status code on any API request.

Can you have them open the browser dev tools via `CTRL + SHIFT + I` or from the app menu and try replicating the issue and checking which API request is giving them the 401? 

https://github.com/jeffvli/feishin/blob/663893dccb551bc28f1e3057c1758c627a9fbb62/src/renderer/api/jellyfin/jellyfin-api.ts#L272-L276

**Comment by pokemonrocks9** [comment] 2023-08-12 14:10
It seems in console we have 
Failed to load resource: the server responded with a status of 401 (Unauthorized)
(Server IP and UserToken)/items?Fields=ChildCount%2C%20Genres%2C%20DateCreated%2C%20ParentId%2C%20Overview&IncludeItemTypes=Playlist&MediaTypes=Audio&Recursive=true&SortBy=SortName&SortOrder=Ascending&StartIndex=0

To add as well I have begun getting the same error

**Comment by pokemonrocks9** [comment] 2023-08-12 14:11
Also have a 
token is expired: undefined
renderer.js:2

Adding a photo of their error 
![tayerrorfeishin](https://github.com/jeffvli/feishin/assets/28373129/5df6f3fa-81a1-41c9-abef-ace66e2bb951)

**Comment by jeffvli** [comment] 2023-08-25 01:19
Sorry for the late response, but I believe this may have had something to do with how the app was fetching playlists (not 100% sure). I've added a way to re-authenticate whenever running into the expired session.

Going to close this for now, but will we can re-open this if you still experience this after the next release.

**Comment by silverfs** [comment] 2023-11-01 18:24
Hi, I hope I am wrong on my end, but from the looks of it, this issue needs to be opened again. 

I have been getting random "session expired" with the same 401 'unauthorized' as seen here in this issue. 
This issue has been present for me and my family members since version 4.0.0, and frequent entry of login credentials has become muscle memory 😅.
I have used Jellyfin 10.8.10 ~and am currently on 10.8.11~, both having the same issue on Feishin.

I mainly use the Windows version of Feishin, but have seen random "expired" sessions on Mac and in the browser version as well.
Is there something I'm missing?

P.S.: Sorry for only reporting this just now, I was incredibly busy.


_edit: I'm currently on 10.8.10, as playlists in 3rd party apps haven't been able to show up on that version yet._

**Comment by Mihara** [comment] 2024-02-16 06:39
I'm also noticing mysterious "session expired" after long disuse with Navidrome, both Navidrome and Feishin running on Linux.

Opening the server edit page and re-saving gets it going again, at least.

**Comment by kgarner7** [comment] 2024-02-16 06:48
> I'm also noticing mysterious "session expired" after long disuse with Navidrome, both Navidrome and Feishin running on Linux.
> 
> Opening the server edit page and re-saving gets it going again, at least.

This is not mysterious; Navidrome's credentials are temporary (https://www.navidrome.org/docs/usage/configuration-options/#:~:text=false-,sessiontimeout,-ND_SESSIONTIMEOUT). When you save the password or re-save the server, it generates new credentials. This is unlike Jellyfin, whose credentials do not expire (as far as I understand)

**Comment by Mihara** [comment] 2024-02-16 16:38
> This is not mysterious;

Session timing out might not be mysterious, what's mysterious is why Feishin does not recreate it automatically like every other client. It has the password and username saved right there, after all.

**Comment by kgarner7** [comment] 2024-02-16 21:50
> > This is not mysterious;
> 
> Session timing out might not be mysterious, what's mysterious is why Feishin does not recreate it automatically like every other client. It has the password and username saved right there, after all.

If (and only if) you selected save password, then it should reauthenticate on failure. But this could also be blocked by #403 (resolved hopefully by #510). If you're using web, the password is never stored

**Comment by kgarner7** [comment] 2024-04-09 06:36
I will be closing this issue as the issue in my earlier comment was addressed (and some better fixes done).

**Closed as completed by kgarner7** 2024-04-09 06:36 UTC
Labels: bug, frozen-due-to-age
