### ISSUE TITLE
Music pausing/un-pausing rapidly for no apparent reason

### ISSUE THREAD

**Issue by dodancs** [jeffvli/feishin#614] opened 2024-05-14 17:41 UTC
### Expected Behavior

I click on a song and it plays.

### Current Behavior

I click on a song, it plays, but also it pauses and un-pauses the song rapidly causing the audio to sound laggy or interrupted.

### Steps to Reproduce

1. Launch Feishin
2. Use it for a while
3. Stop using it for a while with the last song paused or stopped
4. Go back to Feishin and play another song, or just continue the current one, or click on the "Play" button on an album
5. The song starts to play but is being interrupted by constant automatic pausing/un-pausing and cannot be stoped (if you press "Stop" or "Play/Pause", or choose a different song, or press the space bar)

### Possible Solution

Close Feishin and re-open it to solve the issue - but this is not good enough, as now the player has lost all of my previous context (open songs, albums, current song, etc).

### Context

Not sure what causes this issue, but it happens always when I leave the player in paused state in the background for a while (like half an hour, maybe an hour, maybe more). I use mpv instead of the browser player, because I want to use 192khz sample rate and 24bit depth.

MPV settings: `--audio-samplerate=192000 --audio-format=s32`
MPV version: `0.34.1`
Video of the issue happening: https://drive.google.com/file/d/1BioCMZGH_kk9T_ImSa_301BTcz-8sYvk/view?usp=sharing
Video description: I double-clicked a song, it started to play/pause immediately, then I tried to hit stop, and play pause, and space bar, and switch a song, but nothing helped

### Application version

0.7.1

### Operating System and version

Ubuntu 22.04 LTS

### Server and Version

Navidrome 0.52.0

**Comment by dodancs** [comment] 2024-05-14 17:43
Addition:

It happened again, when I freshly launched Feishin, clicked on my playlist in the sidebar, and then clicked on the play button right next to the playlist.
![image](https://github.com/jeffvli/feishin/assets/1970811/4f8f8f25-0950-413d-829c-e77a58a725c2)

**Comment by iiPythonx** [comment] 2024-05-14 17:54
Duplicate of https://github.com/jeffvli/feishin/issues/244, if you can try to upgrade your MPV version (or switch to web player if you're unable to).

**Comment by dodancs** [comment] 2024-05-14 18:11
I think the issue is not with MPV but rather Feishin. There might be a bug that triggers play/pause in rapid succession in the gui. Is there any way I can debug, get logs from the client?

**Comment by iiPythonx** [comment] 2024-05-14 18:19
There's no methods I can think of to do that in the production builds no, maybe @kgarner7 could be of some help here.  
I would still recommend trying a newer MPV version to see if that resolves the issue, considering it did for me and quite a few others.

**Comment by dodancs** [comment] 2024-05-14 18:57
> There's no methods I can think of to do that in the production builds no, maybe @kgarner7 could be of some help here. I would still recommend trying a newer MPV version to see if that resolves the issue, considering it did for me and quite a few others.

Alright, I will try a newer version of mpv, as this is the normal version straight from Ubuntu's distribution. The reason I am using mpv is because I believe web browsers are unable to play high-resolution audio files. Not sure if it is still true, but I just remember I read that somewhere while trying to develop my own thing for playing high-quality audio in the web browser.

**Comment by kgarner7** [comment] 2024-05-14 19:51
There's logging in the ui via inspect element (control/command + shift + I, or open devtools), and also on the executable if you run it in the terminal (mostly mpv logs).

As an aside, WebAudio can have a pretty high sample rate (configurable in Feishin, you can verify if it works with something like EasyEffects; you would need to restart for a new sample rate to take effect)

**Comment by dodancs** [comment] 2024-05-15 06:17
> As an aside, WebAudio can have a pretty high sample rate (configurable in Feishin, you can verify if it works with something like EasyEffects; you would need to restart for a new sample rate to take effect)

Oh, you're right https://caniuse.com/flac , I guess it has been a while since I last checked if browsers supported FLACs. Nevertheless, I will try to investigate the issue with mpv, and if I am not able to come up with any answers, then I will just switch to web audio.

**Comment by kgarner7** [comment] 2024-08-27 03:14
Any updates on this?

**Comment by kgarner7** [comment] 2024-09-07 23:58
Closing for inactivity; if it is still present, please reopen with additional details

**Closed as not planned by kgarner7** 2024-09-07 23:58 UTC
Labels: bug, frozen-due-to-age
