### ISSUE TITLE
Streaming, cover art and other images don't show when the username has URL reserved characters in it

### ISSUE THREAD

**Issue by gravelld** [jeffvli/feishin#841] opened 2024-11-12 16:34 UTC
### Expected Behavior

My username on a Subsonic server includes a "+" character. If I can log into a Subsonic server and display my library, the cover art should also display.

I should also be able to stream music.

### Current Behavior

I am able to login to the server and browse my library. However, no cover art displays. Streaming music does not work.

### Steps to Reproduce

1. Create a user on the Subsonic server with a "+" in the username, e.g. `my+test@example.com`
2. Login to the server with Feishin
3. Observe artwork isn't shown
4. Observe streaming doesn't work.

### Possible Solution

The image and streaming query parameters should be URL encoded.

### Context

I consulted the logs in Astiga and observed that most library browsing calls to `getAlbum` et al do have the username URL encoded (I think because Axios is used; this is default behaviour).

However, the calls to `getCoverArt` do not have the query parameters URL encoded. I think that's because the result of [`getCoverArt()`](https://github.com/jeffvli/feishin/blob/21f4a78dd77c72ce532260a1cb484df6363957fb/src/renderer/api/subsonic/subsonic-normalize.ts#L15) is used verbatim in an HTML element.

### Application version

0.11.1

### Operating System and version

Linux

### Server and Version

Astiga

**Comment by Cambi0nn** [comment] 2024-11-13 09:18
A little add-on (I'm the idiot with + in my email) that streaming itself also doesn't work. @gravelld can better tell if it's caused by only the image call or also by the stream call.

**Comment by gravelld** [comment] 2024-11-13 10:09
> (I'm the idiot with + in my email)

😄

Ah yes! I forgot to mention the streaming - it also looks like that isn't encoded.

**Comment by jeffvli** [comment] 2024-11-14 01:56
Will be fixed in the next version

**Comment by Cambi0nn** [comment] 2024-11-21 08:39
Can it be re-opened? It indeed didn't work after the fix (I had asked @gravelld to look into it as I don't know if it was on Astiga's side or general and I hadn't heard back yet, hence not posting here), but with + not being encoded it also doesn't work.

I would think it would be possible to encode the username only, instead of the whole credentials string?

**Comment by jeffvli** [comment] 2024-11-21 09:04
@Cambi0nn The `+` should be being encoded properly, at least my initial tests.

Are you able to open the browser devtools to check the actual request URL being sent during authentication?

**Comment by Cambi0nn** [comment] 2024-11-21 09:52
Yes, the stream call gives me the following response:
```
<subsonic-response status="failed" version="1.16.0" serverVersion="Astiga/production" xmlns="http://subsonic.org/restapi">
 <error code="40" message="Wrong username or password."/>
</subsonic-response>
```
The coverart call used to do so, but now gives mo response. The images don't load however.

If I look at the payload, the + in my email seems to be a space in both the stream and the coverart calls (if I copy-paste the character it's: " ").

Since I'm logged in just fine and can browse my music, just not play it or see the cover art, I'm pretty sure it's not that my credentials are wrong.

**Comment by jeffvli** [comment] 2024-11-21 09:58
Did you remove and re-add the server in Feishin after the latest release?

**Comment by Cambi0nn** [comment] 2024-11-21 10:11
Goddamit. I swear I did that with every test I did the passed month (I was talking with @gravelld for 2 weeks before it got posted here), beside this one... That did it indeed. Works perfectly!

**Closed as completed** 2024-11-21 10:12 UTC
Labels: bug, frozen-due-to-age
