### ISSUE TITLE
Lyrics are shown as json

### ISSUE THREAD

**Issue by marvix97** [jeffvli/feishin#516] opened 2024-02-18 08:32 UTC
## Expected Behavior

Lyrics are shown as synced and follow the song

## Current Behavior

Lyrics are shown as json

![Screenshot_20240218_091913](https://github.com/jeffvli/feishin/assets/6461519/e30cd549-0ebf-4392-983a-e7243ebe6d1b)

There is nothing relevant in the dev tools console, no errors.

## Steps to Reproduce

1. Play a song

2. Go to the lyrics tab

## Context

I noticed that lyrics stopped working after an update to my navidrome container and I forced a full rescan of the library, maybe it's related, since it used to work fine before. 

Could it be that navidrome updated the way of sending lyrics to a client? But I don't know, since in Symfonium it still works right

## Your Environment

-   Application version (e.g. v0.1.0) : v0.5.3
-   Operating System and version (e.g. Windows 10) : Arch Linux
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome v0.51.1
-   Node version (if developing locally) :

**Comment by kgarner7** [comment] 2024-02-18 14:41
Duplicate of https://github.com/jeffvli/feishin/issues/468, already resolved in development. Check out https://feishin.vercel.app for how it looks

**Closed as completed by kgarner7** 2024-02-18 14:41 UTC
Labels: bug, frozen-due-to-age

**Comment by HoreaM** [comment] 2024-02-19 09:37
> Duplicate of #468, already resolved in development. Check out https://feishin.vercel.app for how it looks

Hi, is there a docker image that has this fix? I tried the development tag, but it seems like it's not included there yet. Thanks!

**Comment by kgarner7** [comment] 2024-02-19 15:50
For one, the `development` tag is actually older than all the other branches. But no, there is no published Docker image with this currently (the only place that has it is the vercal page).
