### ISSUE TITLE
Toggling shuffle restarts playback, shows incorrect track/duration

### ISSUE THREAD

**Issue by swishkin** [jeffvli/feishin#540] opened 2024-03-13 03:13 UTC
## Expected Behavior

Toggling shuffle while playing from the middle of an album/playlist should reorder the current play queue, not interrupting the current song's playback.

## Current Behavior

Feishin begins playing the first song in the playlist/album when you toggle shuffle on, but still shows the previous (mid-album) song title, duration, etc. Toggling shuffle on again returns to the previous (mid-album) song.

## Steps to Reproduce

1. Play a song from the middle of an album or playlist.

2. Toggle shuffle.

3. Feishin will switch playback to the first song in the playlist/album, then back to the mid-playlist/album song if toggled again.

## Context

Switching between shuffled and ordered playback is disrupted.

## Your Environment

-   Application version (e.g. v0.1.0) : Feishin 0.6.0
-   Operating System and version (e.g. Windows 10) : Artix Linux 6.7.9
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.51.1 (6d253225)
-   Node version (if developing locally) : N/A

**Comment by kgarner7** [comment] 2024-03-31 00:54
I am not able to reproduce this at all. Are you saying that the shuffle button in the center changes the currently playing track? What player are you using: web or MPV?

**Comment by swishkin** [comment] 2024-03-31 01:25
Ok, so I'm not encountering this anymore; either 0.6.1 has resolved this issue or I didn't accurately reproduce the situation it occurred in.

I was using the Linux desktop client, installed from the AUR. I might try downgrading and testing 0.6.0 just to see if I can reproduce it there.

**Comment by kgarner7** [comment] 2024-04-12 18:18
Checking in here, were you able to reproduce this with an older version? And have you seen it at all in 0.6.1 (or the web version)?

**Comment by Amatsu-Kami** [comment] 2024-05-02 13:29
I have this problem, but only if I manually select a track that is not the first track. And it only does it for the first track that is manually selected. If I skip to the next song, I don't have the bug anymore. I'm on 0.6.1 of the docker version.

**Comment by kgarner7** [comment] 2024-08-20 04:40
Checking in again; I am unable to reproduce this using 0.7.3 web. Is this issue still present?

**Comment by Amatsu-Kami** [comment] 2024-08-20 14:53
yes, steps to reproduce:
1: Click on shuffle 
![image](https://github.com/user-attachments/assets/3a7e80f9-e29f-4249-8a23-9358a33acbe1)
2: Go in an album and manually select a track that isn't the first track.
3: Click on shuffle again to remove the shuffle, it will still be on the same song, but the audio will be the first song of the album
4: If you click on shuffle again, the audio will go back to the song you manually selected.

If you skip the song you manually selected, the bug is not present.

I'm using firefox, not sure if that matters.

**Comment by kgarner7** [comment] 2024-08-21 02:11
Resolved by https://github.com/jeffvli/feishin/commit/a537642990ccce2dcc7604ad56507ea66425c1bf

**Closed as completed by kgarner7** 2024-08-21 02:11 UTC
Labels: bug, frozen-due-to-age
