### ISSUE TITLE
Volume stays at previous value for a split second while paused

### ISSUE THREAD

**Issue by sammy-ette** [jeffvli/feishin#325] opened 2023-10-23 21:05 UTC
## Expected Behavior
If music is adjusted while paused, it should change the value immediately, not right when music starts to play again.

## Current Behavior

When music is paused and volume is adjusted, itll stay at the previous value for a very small amount of time. It is very noiceable when going from high to low.

## Steps to Reproduce

1. Play any song (maybe for a few seconds)
2. Pause it
3. Change the volume to something low
4. Play again and notice the jump in volume

https://github.com/jeffvli/feishin/assets/38820196/8fbbeed4-2acd-46c0-9863-1b9e17c46c23

(Also features another bug of negative duration?)

## Your Environment

-   Application version (e.g. v0.1.0) : v0.4.1
-   Operating System and version (e.g. Windows 10) : Fedora Linux 38
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin v10.8.11
-   Node version (if developing locally) :

**Comment by kgarner7** [comment] 2024-02-08 05:32
I am currently not able to reproduce this issue with either MPV or Web Audio backend (using latest build), is this still an issue?

**Comment by iiPythonx** [comment] 2024-02-08 05:45
I also don't have this issue anymore, I'm *pretty sure* it got fixed *around* 0.5.1?
(it did used to happen to me as well)

**Comment by sammy-ette** [comment] 2024-02-14 23:38
Still happens on MPV but not on Web, though I'm on the subsonic branch but that should still be newer than 0.5.1

**Comment by iiPythonx** [comment] 2024-02-14 23:42
Are you using a supported version of mpv (v0.35+)? I haven't had this issue in quite a long time.

**Comment by sammy-ette** [comment] 2024-02-14 23:45
```
~ 
∆ mpv --version
mpv v0.36.0-530-g273906490d Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Oct 13 2023 19:10:17
libplacebo version: v6.338.0-30-g7ca8418f
FFmpeg version: N-112456-g90d327d607
FFmpeg library versions:
   libavutil       58.27.100
   libavcodec      60.30.102
   libavformat     60.15.100
   libswscale      7.4.100
   libavfilter     9.11.100
   libswresample   4.11.100
```

Right from the Fedora repositories.

**Comment by iiPythonx** [comment] 2024-02-14 23:54
Strange that it would happen to you on both MPV and web. It works for me on both Windows & Linux:

https://github.com/jeffvli/feishin/assets/35084023/5f4285aa-7739-4436-9c96-ef86105afd07

(using the mpv backend in that example, but web does the same thing)


Random idea, but since the subsonic branch is 100 commits behind development, you might want to clone development locally, merge the subsonic PR yourself, and then build and test. It might of been fixed somewhere in between the two branches.

**Comment by kgarner7** [comment] 2024-02-17 20:45
> Still happens on MPV but not on Web, though I'm on the subsonic branch but that should still be newer than 0.5.1

The subsonic branch is ahdead of 0.5.1 but behind 0.5.3, and very behind current development (as noted above). Can you please try https://github.com/jeffvli/feishin/actions/runs/7940626880 (recent development build)

**Comment by kgarner7** [comment] 2024-04-10 06:22
Since this issue has not been reproduced, and there have been no further updates/testing on newer releases, I am going to close this issue. If it still is reproducible on the most recent release, please open this issue again with further details.

**Closed as completed by kgarner7** 2024-04-10 06:22 UTC
Labels: bug, frozen-due-to-age
