### ISSUE TITLE
Repeat one mode not repeating song.

### ISSUE THREAD

**Issue by NebulaAnimations** [jeffvli/feishin#414] opened 2023-12-18 14:43 UTC
## Expected Behavior

With repeat one mode on it should loop and replay the currently selected song.

## Current Behavior

Once the song ends it jumps back to timecode 0 for the song in play however it dosent actually begin to play the track.
![Feishin_btq1E3AyJw](https://github.com/jeffvli/feishin/assets/70425584/75a9ce3b-6106-4f6a-9c0c-1f7f3723ef7e)

## Steps to Reproduce

1. Select song

2. Set to repeat one

3. Upon song completion track remains stuck at timecode 0 in play mode.

## Possible Solution (Not obligatory)

Unsure, unfortunatly not a developer

## Context

I tend to leave a song on repeat when doing some work when i find a good track and that is how i discovered the issue.

## Your Environment

-   Version 0.5.3
-   Windows 11
-   Navidrome V0.50.2

**Comment by kgarner7** [comment] 2024-01-28 08:54
Resolved by https://github.com/jeffvli/feishin/commit/47ce0ed47b1518440a05956e3161806e05b931b0 (behavior on web player was even worse). 
This issue happened only if 1. You have repeat 1, 2: you have shuffle, and 3: you are on the first element of the queue and was caused by. Thanks for the picture, as not seeing the shuffle would've made this harder to reproduce

**Closed as completed by kgarner7** 2024-01-28 08:53 UTC
Labels: bug, frozen-due-to-age
