### ISSUE TITLE
Jellyfin 10.9 has a different Lyrics API endpoint? 

### ISSUE THREAD

**Issue by Eeeeelias** [jeffvli/feishin#584] opened 2024-04-12 22:06 UTC
## Expected Behavior

Lyrics should be displayed when playing a song that has lyrics on Jellyfin version 10.9

## Current Behavior

No lryics are showing. Feishin is requesting Lyrics from `/users/{user_id}/Items/{item_id}/Lyrics` but that returns a 404 code no matter what. The Lyrics definitely exist and show in the Jellyfin Web "Media Info".

## Steps to Reproduce

1. Install Jellfin version 10.9 unstable (I am running it in docker)

2. Play a song that has Lyrics (also confirmed by Jellyfin)

## Possible Solution (Not obligatory)

While https://github.com/jellyfin/jellyfin/pull/8381 suggests that the lyrics should be at  `/users/{user_id}/Items/{item_id}/Lyrics`, when I look up the jellyfin-api docs at `/api-docs/swagger` they specify to look for the lyrics at `/audio/{item_id}/lyrics`. 
I tried to call this endpoint with an example song and that does return the correct lyrics.

## Context

I'm currently trying the newest Jellyfin unstable version in anticipation of the release and found that while the Lyrics API endpoint exists, it seems like it's not exactly where it was expected to be. I'm not sure if this endpoint is intentional since in the original PR it was different.

## Your Environment

I tried both Docker & the Windows app. My Jellyfin server is on the latest unstable 10.9 version.

**Comment by kgarner7** [comment] 2024-04-12 22:17
Duplicate of #535. Since the initial implementation, the endpoint has changed and I'm not too keen on any work until it is stable. When Jellyfin becomes stable and the API is documented on https://api.jellyfin.org/, I can take a look.

**Closed as not planned by kgarner7** 2024-04-12 22:17 UTC
Labels: bug, frozen-due-to-age

**Comment by NicholasFlamy** [comment] 2024-04-22 23:55
> The Lyrics definitely exist and show in the Jellyfin Web "Media Info".

That was previously broken, I think because they changed API endpoints, so I opened an issue on Jellyfin and they fixed it a few months ago.
