### ISSUE TITLE
Smart Playlist Sort Order doesn't work

### ISSUE THREAD

**Issue by Fluttrr** [jeffvli/feishin#163] opened 2023-06-24 09:21 UTC
## Expected Behavior

Creating a smart playlist gives the option of a sort order which should sort the playlist

## Current Behavior

No matter what order you choose, it always sorts alphabetically. Not sure if this is some issue on my end but in the Symfonium app it works fine.

## Steps to Reproduce

1. Create smart playlist

2. Choose sort order, for example random (none of the ones i tried work)

![image](https://github.com/jeffvli/feishin/assets/12749059/07e5b500-af59-4c72-8b49-58775be7cf42)

4. You should see it's just sorted alphabetically anyway

![image](https://github.com/jeffvli/feishin/assets/12749059/cfcf6d6c-7629-4116-84b6-0c878b2e3aa0)

## Your Environment

- Application version (e.g. v0.1.0) : 2.0.0
- Operating System and version (e.g. Windows 10) : Windows 11
- Server and version (e.g. Navidrome v0.48.0) : Navidrome v0.49.3

**Comment by isle9** [comment] 2023-06-25 11:18
That sort is for when you're using the limit function. If you have 500 songs in a playlists, and limit it to 100, the app needs to decide which songs to show you.

1. If you want to properly sort the playlist, you need to open it fully. Next to the play button, you see the "VIEW FULL PLAYLIST" button. Click on that.
2. Now you can use the normal sort function, and sort the playlist however you want.

![image](https://github.com/jeffvli/feishin/assets/74906541/723388fc-9584-4a45-b0c7-ee750b63ad55)

**Comment by Fluttrr** [comment] 2023-07-02 11:25
I suppose that is a workaround, but is there no way to have it sorted even in the shortened view? I mean it is sorted alphabetically by title so some sort of sorting does take place, but I'm not sure if maybe that is just done by navidrome.

Another issue is that even in this full view, if you sort the playlist and play a song, the queue does not follow the sorting order. I can sort by album and when I play a song my queue will still be sorted by track name, which makes the sorting feature for playlists kinda useless

**Comment by isle9** [comment] 2023-07-02 12:33
> I suppose that is a workaround, but is there no way to have it sorted even in the shortened view? I mean it is sorted alphabetically by title so some sort of sorting does take place, but I'm not sure if maybe that is just done by navidrome.

You can still use the sort at the bottom of the query to sort in the short view iirc.

> Another issue is that even in this full view, if you sort the playlist and play a song, the queue does not follow the sorting order. I can sort by album and when I play a song my queue will still be sorted by track name, which makes the sorting feature for playlists kinda useless

This one's' a bug. If was gonna write a bug report, but forgot about it.

**Comment by Fluttrr** [comment] 2023-07-02 14:30
I'm not quite sure what you mean with "the sort at the bottom of the query", are you sure it's possible?
Edit: If you mean the one when you create a playlist, that doesn't work. Even in the extended playlist view it was no effect because you have to choose the sort order yourself.

**Comment by isle9** [comment] 2023-07-02 14:33
> I'm not quite sure what you mean with "the sort at the bottom of the query", are you sure it's possible? Edit: If you mean the one when you create a playlist, that doesn't work. Even in the extended playlist view it was no effect because you have to choose the sort order yourself.

![image](https://github.com/jeffvli/feishin/assets/74906541/8e7e1091-39cf-447d-bd54-31f7985e105e)

Yes, this one.
It works for me... In both the short and the full views of the playlist.

**Comment by Fluttrr** [comment] 2023-07-02 14:34
Yes, for ascending name it works because that's the default order, if you change it to anything else like the example I showed above, at least for me, it does not work

**Comment by isle9** [comment] 2023-07-02 14:34
> Yes, for ascending name it works because that's the default order, if you change it to anything else like the example I showed above, at least for me, it does not work

I'll give you an example with albums which works for me.

Regular
![image](https://github.com/jeffvli/feishin/assets/74906541/f6b10786-1471-4329-9e94-061fd0565f6f)

Full
![image](https://github.com/jeffvli/feishin/assets/74906541/a891d1db-e4ed-4e86-9d08-d4b064897ac1)

Query
![image](https://github.com/jeffvli/feishin/assets/74906541/1fc0fde1-a493-4b71-9210-095ae8b4bee6)

**Comment by Fluttrr** [comment] 2023-07-02 14:38
Interesting, for me it doesn't work:

![image](https://github.com/jeffvli/feishin/assets/12749059/b04d9319-1d25-4202-a734-7adcc7eb17f4)

![image](https://github.com/jeffvli/feishin/assets/12749059/b7bdaf66-b850-488f-b817-2e58cc5f0b2b)

![image](https://github.com/jeffvli/feishin/assets/12749059/d681526d-099c-4eb0-805a-fcba87572d8b)

But it's weird too because your full playlist view shows it's sorted by ID at the top and not by album? I'm very confused about all of this, it's really weird

**Comment by isle9** [comment] 2023-07-02 14:41
> Interesting, for me it doesn't work:
> 
> ![image](https://user-images.githubusercontent.com/12749059/250363818-b04d9319-1d25-4202-a734-7adcc7eb17f4.png)
> 
> ![image](https://user-images.githubusercontent.com/12749059/250363861-b7bdaf66-b850-488f-b817-2e58cc5f0b2b.png)
> 
> ![image](https://user-images.githubusercontent.com/12749059/250363870-d681526d-099c-4eb0-805a-fcba87572d8b.png)
> 
> But it's weird too because your full playlist view shows it's sorted by ID at the top and not by album? I'm very confused about all of this, it's really weird

Yes, you should use the id in the full playlist view. That uses the sort you used in the query.

Try reloading feishin or the playlist itself, that fixes it sometimes.

**Comment by Fluttrr** [comment] 2023-07-02 14:44
Interesting, reloading did nothing but I found a fix, if you go to the full playlist view, use the query editor there, then save and replace the playlist it does work. Just wondering why it doesn't work right away.

**Comment by isle9** [comment] 2023-07-02 14:45
> Interesting, reloading did nothing but I found a fix, if you go to the full playlist view, use the query editor there, then save and replace the playlist it does work. Just wondering why it doesn't work right away.

I was about to write that exact workaround lol.

**Comment by isle9** [comment] 2023-07-16 14:23
@jeffvli Should this be closed or maybe the title should changed?

**Comment by Fluttrr** [comment] 2023-07-16 14:29
I mean the issue is still a thing at least for me, it's not really optimal to have to edit, save and replace every smart playlist I create, I'm just not sure if this is somehow an issue only on my end of course.

And the queue sort order not being applied is also still another issue of course.

**Comment by jeffvli** [comment] 2023-07-17 07:01
I just went through and confirmed it wasn't working. Turns out I was accidentally setting the wrong properties on the create playlist popup. Should be fixed in the next release.

**Closed as completed by jeffvli** 2023-07-17 07:01 UTC
Labels: bug, frozen-due-to-age
