### ISSUE TITLE
Add cast features (chromecast...)

### ISSUE THREAD

**Issue by SeeDborg** [jeffvli/feishin#423] opened 2023-12-26 21:31 UTC
Hi,
I love your app and I would love to be able to cast the music on my chromecast devices on the network.

Would it be possible to implement it ?

Regards.

**Comment by kgarner7** [comment] 2024-04-10 07:00
This is a duplicate of #256; if any updates happen please refer to the linked issue instead.

**Closed as not planned by kgarner7** 2024-04-10 07:00 UTC
Labels: enhancement, frozen-due-to-age
