### ISSUE TITLE
Release dates in discography view are displayed as timestamps

### ISSUE THREAD

**Issue by Hydronicx** [jeffvli/feishin#620] opened 2024-05-17 23:39 UTC
### Expected Behavior

Release dates should be displayed in the format they are given in the tags (e.g. just the year, or YYYY-MM-DD).

### Current Behavior

In the "view discography" of an artist, release dates of albums display as full timestamps no matter the original format (e.g. 1997-01-01T05:00:00.000Z).

### Steps to Reproduce

1. Go to the artist page.
2. Click "View discography".
3. Check the release dates of the albums.

### Possible Solution

Format the release dates appropriately.

### Application version

0.7.1

### Operating System and version

Web client

### Server and Version

Navidrome 0.52.5

**Comment by kgarner7** [comment] 2024-05-25 14:47
I am unable to reproduce this, as they are all in `short month, day, year` format for me. Can you confirm if this behavior is also seen on https://feishin.vercel.app?

**Comment by ahmadelf** [comment] 2024-05-25 17:38
Sorry, it seems like I was confused. I think I was looking at the albums sorted by "recently played" and it actually displayed the timestamp of the last play, which I must have confused for the release date because I was looking at a recent album.
(Also, it seems like when sorting by "duration", it shows the duration in ms.)

**Comment by Hydronicx** [comment] 2024-05-25 17:39
Sorry, I must have confused the release date with the timestamp of the last play (in the "recently played" sorting order).
(Also, I noticed that the duration shown in the "duration" sort seems to be given in ms without any formatting of hours, minutes, seconds.)

**Comment by kgarner7** [comment] 2024-05-25 17:45
Please test this behavior on latest web. None of what you describe is what currently exists
![image](https://github.com/jeffvli/feishin/assets/17521368/854cad8a-b7f9-47b8-a2e6-2104028be728)

**Comment by Hydronicx** [comment] 2024-05-26 18:04
I should have noted that this is only an issue in the card and poster views, not the table view.

**Comment by kgarner7** [comment] 2024-05-26 18:08
Please include a screenshot of this behavior from https://feishin.vercel.app, as I am not able to reproduce this either.

**Comment by iiPythonx** [comment] 2024-05-26 18:17
This does in fact happen, strictly with the recently played sort order though:
![image](https://github.com/jeffvli/feishin/assets/35084023/d30a11ea-0171-4463-b97a-17d77a7769c6)

(And I can also reproduce the sort by duration view showing milliseconds)

**Comment by kgarner7** [comment] 2024-05-26 19:27
Resolved by https://github.com/jeffvli/feishin/commit/aa89c5e80ec95ac1880f4a3895afe45a9518ef35. In the future, it would be helpful if you could also include screenshots of your issue. Thanks iiPythonx for the clarification!

**Closed as completed by kgarner7** 2024-05-26 19:27 UTC
Labels: bug, frozen-due-to-age
