### ISSUE TITLE
SyncPlay Group support for JellyFin

### ISSUE THREAD

**Issue by auyylaso** [jeffvli/feishin#453] opened 2024-01-19 06:05 UTC
## What do you want to be added?
Support for SyncPlay groups for JellyFin

## Additional context
JellyFin has this option to use something called SyncPlay in a group it essentially lets you listen to music with your friends or family. Or allows you to sync up multiple devices to play the same audio at the same time.

JellyFin

**Comment by Bestfast** [comment] 2024-01-19 07:04
Jellyfin SyncPlay groups are pretty broken and probably will always be, as the developer doesn't actively work on it (in fact, the code for groups etc is very old). An approach within Feishin itself would be probably better, imo

**Comment by kgarner7** [comment] 2024-04-01 01:42
Closing this as it is a duplicate of #352

**Closed as not planned by kgarner7** 2024-04-01 01:42 UTC
Labels: enhancement, frozen-due-to-age
