### ISSUE TITLE
Albums missing, Win11 & unRAID container jellyfin

### ISSUE THREAD

**Issue by sihorrocks** [jeffvli/feishin#174] opened 2023-07-08 01:29 UTC
## Expected Behavior

 albums should display in albums view and in artist view, both remain empty. The album is listed within track and artist meta data correctly, but the tracks cannot be viewed as an album within the software.

 In addition, where collabs are listed on an artist, this is broken out as a separate artist listing, would be preferable for the tracks to be listed by primary artist, (or album artist) not as a new wholly separate artist.

These same problems are present in sonixd, jellyfin lists albums accurately as does win media player

## Current Behavior

Albums list is empty, no albums listed in artist view, tracks display okay, new artist listing is created for Collab songs with multiple artist

## Steps to Reproduce

1. Windows 11

2. Jellyfin server running on unraid app container 

3. Install feishin on win 11

4. Connect to jellyfin server via unRAID app container local IP address 
5. Import server, no albums listed, when in artist view lists only tracks not albums.

## Context

 Looking for a fully featured jellyfin compatible audio player to replace jelly fin for local audio playback

## Your Environment

-   Application version (e.g. v0.1.0) : current version 
-   Operating System and version (e.g. Windows 10) : windows 11
-   Server and version (e.g. Navidrome v0.48.0) : jellyfin unRAID app container, binhex, latest version
-   Node version (if developing locally) :

**Comment by jeffvli** [comment] 2023-07-17 07:09
I'm running on the same setup with unraid/docker and I'm unable to reproduce this.

If you open up the browser devtools from the app and navigate to the album list page.

![image](https://github.com/jeffvli/feishin/assets/42182408/04f44262-f152-45bf-835b-285a1b2be856)

Check the following:

1. Check that the request URL is not malformed: 
![image](https://github.com/jeffvli/feishin/assets/42182408/e00ded6e-8e21-4e8e-a928-f39d4cf8287d)

2. Check if the API is properly returning results: ![image](https://github.com/jeffvli/feishin/assets/42182408/6aebe1ed-b8c4-4ab7-97a0-c8262bbaa0b8)

I'm thinking this may be some weird permission issue or some configuration that I'm not aware of (or possibly you may need to update your Jellyfin container).

**Comment by sihorrocks** [comment] 2023-07-18 21:41
Haven't had time to sit down with it just yet, I will give it a look today, and may try on a different machine too.

**Comment by sihorrocks** [comment] 2023-07-20 01:16
I've installed on another machine, same basic setup, still has the album issue. Album meta data is there in Feishin see example
![album metadata](https://github.com/jeffvli/feishin/assets/138950187/80c1e975-4d21-476f-81bb-b2a4e33f7353)
album sorting works in the jellyfin player too see example
![jellyfin albums](https://github.com/jeffvli/feishin/assets/138950187/bb28b590-1630-4a93-9993-249b75123d0f)
Also ran an app using the SMB share on my unraid server, and was able to show and sort by albums. 
Checked the API request as requested, not an expert here but it looks okay 
![albums api](https://github.com/jeffvli/feishin/assets/138950187/6a4902ec-df0c-4fe4-b9fb-d741ca8b3c01)
However I note in the preview, TotalRecordCount is 0 of 0
![albums api 1](https://github.com/jeffvli/feishin/assets/138950187/90a068e5-d433-493d-97fa-9f3973a355e8)
Tracks api seems to work okay calling the correct number of records
![tracks api 1](https://github.com/jeffvli/feishin/assets/138950187/cd9bee6a-81e7-44e9-94e3-89506754d182)
![tracks api preview 2](https://github.com/jeffvli/feishin/assets/138950187/194fd7cf-6873-4de1-9741-ea1a9885ef6f)
Also have no playback on new install, no audio, playback doesnt commence no details in Feishin 
![playing from unraid](https://github.com/jeffvli/feishin/assets/138950187/ded5ed74-2e71-4f6c-a60a-ebfe5a428d21)
Unraid jellyfin permissions look accurate - using Trash guides setup
![unraid jellyfin](https://github.com/jeffvli/feishin/assets/138950187/9f86e291-314d-4f46-b0f7-67c1b7b49835)
Jellyfin user permissions look good also
![jellyfin permissions](https://github.com/jeffvli/feishin/assets/138950187/491e0e12-17db-4c75-bf1b-feca49824deb)

Willing to try anything else you might suggest?

**Comment by jeffvli** [comment] 2023-07-20 01:22
![image](https://github.com/jeffvli/feishin/assets/42182408/7890e2be-2dcf-4e43-b80e-8d43712849d6)

Try selecting and de-selecting a folder from the folder filter. You may have selected a previously deleted folder which is then causing the filter to return 0 results. I just remembered that could potentially be an issue (especially when switching between different Jellyfin servers).

If that doesn't work then we'll have to do some more troubleshooting.

**Comment by sihorrocks** [comment] 2023-07-20 02:39
Had a go, the button doesn't seem to do anything at all
![20230720_142855](https://github.com/jeffvli/feishin/assets/138950187/529cea36-4484-443d-aeee-c83980d8a6f1)
Sorry for the phone pics, using my htpc for playback

Added folders to the side menu, and it flings up this error
![20230720_142830](https://github.com/jeffvli/feishin/assets/138950187/c96dff9b-d079-4cfe-9293-05a2803cb7c2)
Genres is the same
![20230720_142840](https://github.com/jeffvli/feishin/assets/138950187/541a4bda-92ed-4253-bc06-848a1c3ece02)
Albums just blank
Also the homepage remains blank and won't update looks like part of the same issue
![20230720_142816](https://github.com/jeffvli/feishin/assets/138950187/22f1607b-f01d-4328-9548-12dd8d023ba9)

Audio playback will only work on web player too, not sure if that related

**Comment by jeffvli** [comment] 2023-07-21 07:27
Couple more things to try:

- Are you using a different account than your main/admin Jellyfin account to log in to Feishin?
    - If so, try checking your user permissions to make sure you have access
- Try updating to the latest Jellyfin server version if not already
- Try uninstalling Feishin -- and then deleting the install folder from `%appdata%/feishin`, and then reinstalling
- Open Feishin and press `CTRL + SHIFT + i` to open the devtools. Navigate to the `Application` tab and look for `Local Storage`. Delete all the entries and restart the app

If all else fails, maybe try asking on the Jellyfin discord server, they may have encountered this issue before.

**Comment by kgarner7** [comment] 2024-08-26 05:53
There hasn't been activity in this for over a year. If it is still an issue, please chime and reopen, but for now I will close this issue.

**Closed as not planned by kgarner7** 2024-08-26 05:53 UTC
Labels: bug, frozen-due-to-age
