### ISSUE TITLE
Random white screen and audio stops

### ISSUE THREAD

**Issue by Hushworkz** [jeffvli/feishin#834] opened 2024-11-09 20:09 UTC
### Expected Behavior

App should run normally without experiencing this.

### Current Behavior

The app turns into an entierly white screen, the audio stops ( but doesn't glitch out ), and the feature to remember the queue resets to the state before last app launch.

Here is also the errors i got in the dev menu:
![Screenshot 2024-11-09 204831](https://github.com/user-attachments/assets/cf3712e7-e184-4c22-9b9c-d30cfc509505)

Something i also noticed is that the album view sometimes unloads randomly, that causes the error below.
`[Violation] 'setTimeout' handler took 57ms`

Clicking on the left upper search button and using some of the "go to page" buttons, causes this error:
`[Violation] 'message' handler took 150ms`

When the app freezes the big red errors pop up.

### Steps to Reproduce

Play around with the app, playing different songs going in to different menus and link. I don't think there is any specific action that causes it, but i probably just haven't noticed yet.

### Context

It is fairly annoying, but not really critical for me. It started randomly happening ( commonly when exploring a lot of menus and links ). A restart of the app fixes it, though it resets the queue as i said.

Another thing i should probably metion is that im running a kinda weird setup. I open jellyfin on my pc when i listen to music, and also open up feishin and have it connect to the "server" through localhost. It's probably overkill, but it works well for me. I don't know if this could cause this issue but i don't think so.  

### Application version

0.11.1

### Operating System and version

Windows 11 23H2 (OS Build 22631.4317)

### Server and Version

Jellyfin 10.10.0

**Comment by jeffvli** [comment] 2024-11-14 02:09
It seems like it's erroring out when accessing a list page (probably Albums or Tracks). If you can reproduce it again you would want to check the `Network` tab of the browser devtools, filter by `Fetch/XHR`, and then check the latest fetches to see if they're returning valid data.

**Comment by Hushworkz** [comment] 2024-11-14 22:16
I don't really see anything obviously wrong with it. It seems to be happening when scrolling through lists, especcially the album page. The data isn't quite right though, the userdata field on some of them returns wrong values, f.e. playcount: 0, when i have listened to the album. It also likes to push alot of warnings when pressing the "go to page" buttons. Though thats probably irrelevant. Here i provide some of the data that i see, maybe im not looking in the right place.
![Screenshot 2024-11-14 231229](https://github.com/user-attachments/assets/ed486c50-1081-4571-8348-51bc44e938fc)

**Comment by jeffvli** [comment] 2024-11-15 05:04
Actually the error you're getting seems to indicate that it's erroring out when rendering the skeleton loaders on the list pages (though I'm not sure why that would happen). 

Maybe there's something wrong with one of the sort options which is causing the error. What sort option do are you using on the album list page?

**Comment by Hushworkz** [comment] 2024-11-15 18:01
Im am using the A-Z option, or name it's probably called.

**Comment by Woytsekj** [comment] 2024-11-16 17:45
I am also getting this white screen but this happens whenever it feels like when shuffling. But with these error logs, the issue is not just produced with one thing.
I am using Navidrome 0.53.3
![image](https://github.com/user-attachments/assets/3c9c7280-71e4-457a-9e1f-4e13aeacbaf3)
![image](https://github.com/user-attachments/assets/a012ebff-a0d4-4ca5-8304-9f7587d03b98)

**Comment by jeffvli** [comment] 2024-11-19 04:19
@Woytsekj Pushed a fix that should hopefully resolve your crashes.

@Cubicalspy I pushed a fix for your issue as well (I think). I'm still not sure exactly why your error is occurring, but hopefully this resolves it. Re-open if it occurs after the next release.

**Closed as completed by jeffvli** 2024-11-19 04:19 UTC
Labels: bug, frozen-due-to-age
