### ISSUE TITLE
Now Playing screen customization of components broken

### ISSUE THREAD

**Issue by NicholasFlamy** [jeffvli/feishin#595] opened 2024-04-24 02:09 UTC
So the bottom option where you can add or remove components doesn't work in the Now Playing Screen.

![Screenshot 2024-04-23 220603](https://github.com/jeffvli/feishin/assets/30300649/d369eab0-4c83-4904-a71a-44edd6bfd6b3)
![Screenshot 2024-04-23 220817](https://github.com/jeffvli/feishin/assets/30300649/82aea1ab-95f2-4498-8ba3-4cf00573c910)
![Screenshot 2024-04-23 220824](https://github.com/jeffvli/feishin/assets/30300649/81b3d67d-a3da-44f8-92e4-2c314bf6fdbe)

Also, after reopening the app it shows the default values.

**Comment by kgarner7** [comment] 2024-04-24 14:47
Resolved by https://github.com/jeffvli/feishin/commit/dc95a3c66be2b745cd0e89911d86382881db7039

**Closed as completed by kgarner7** 2024-04-24 14:47 UTC
Labels: bug, frozen-due-to-age

**Comment by NicholasFlamy** [comment] 2024-06-11 00:43
Now it saves your changes, but I don't think the changes are actually visible. I'm not able to edit the now-playing screen.

**Comment by NicholasFlamy** [comment] 2024-11-19 12:24
@kgarner7 it was never truly fixed. Like it never worked (for me at least).

Please reopen the issue.

Small rant:
Why was Sonixd rewrote to Feishin only now to be rewritten to audioling. This seems like the perfect example of CADT: https://www.jwz.org/doc/cadt.html

**Comment by NicholasFlamy** [comment] 2024-11-19 12:25
P.S. tested on Windows.

**Comment by jeffvli** [comment] 2024-11-19 13:13
I'm unable to reproduce. Try clearing your `store_settings` key in the localstorage and restarting the app (though this will reset your settings).

I already gave my justification for rewriting the app. I also do it as a **hobby** and for my **professional development** since I get to test out new libraries and the latest web dev trends. Being open source, anyone who is willing to put in the time and effort can fork and maintain Feishin if they want to. The problem is that there's very little incentive to for someone to want to spend their precious time doing work for no gain.

**Comment by NicholasFlamy** [comment] 2024-11-19 13:57
> I already gave my justification for rewriting the app. I also do it as a **hobby** and for my **professional development** since I get to test out new libraries and the latest web dev trends. Being open source, anyone who is willing to put in the time and effort can fork and maintain Feishin if they want to. The problem is that there's very little incentive to for someone to want to spend their precious time doing work for no gain.

Sorry about the small rant, I had to get it out. I hope I didn't upset you too much. I get it that this is a hobby and that you aren't being paid to maintain this. I appreciate the work you put in.



> Try clearing your `store_settings` key in the localstorage and restarting the app (though this will reset your settings).

I will try this soon and report back.
