### ISSUE TITLE
Fails to play any song after windows sleeps

### ISSUE THREAD

**Issue by CrepeTF** [jeffvli/feishin#187] opened 2023-07-20 10:34 UTC
## Expected Behavior

Playback should work

## Current Behavior

When windows wakes up from sleep state and there's an attempt at playing a song. The song is not played and the program has to be restarted.

## Steps to Reproduce

1. Leave feishin in the background - song paused

2. Let windows enter sleep state

3. Wake up windows

4. Try to play a song

## Possible Solution (Not obligatory)

N/a

## Context

There's times when I wish to leave my pc idle but when I get back to it windows enters sleep mode to conserve energy. However upon coming back I always have to restart feishin if I want to play a song as playback would not work otherwise.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.2.0
-   Operating System and version (e.g. Windows 10) : Windows 11  (22621)
-   Server and version (e.g. Navidrome v0.48.0) : Jellyfin 10.8.10
-   Node version (if developing locally) : N/a

**Comment by kgarner7** [comment] 2024-03-02 05:38
I tested latest build on w11 and I'm not able to reproduce this, is it still an issue? 
What version of MPV are you using, and where did you get it? (winget/sourceforge/choco?)
Does it also happen with web player?

**Comment by CrepeTF** [comment] 2024-03-22 19:23
Hey, quick update, it is still happening but I've actually had a look at the network requests for the issue. It was stuck waiting for server response

**Comment by kgarner7** [comment] 2024-03-26 05:54
Just to be clear, where is your Jellyfin server hosted? Is it also on windows? What specifically is Feishin waiting on?

**Comment by kgarner7** [comment] 2024-08-20 05:14
Since there have not been updates to this issue for quite a while, I'm going to go ahead and close it. If this is still an issue, please feel free to reopen.

**Closed as not planned by kgarner7** 2024-08-20 05:14 UTC
Labels: bug, frozen-due-to-age
