### ISSUE TITLE
Navidrome Discord RPC icon support

### ISSUE THREAD

**Issue by flysqu** [jeffvli/feishin#552] opened 2024-03-19 17:18 UTC
## What do you want to be added?
Currently discord rpc icons only work on jellyfin. Would be nice to have this on navidrome too. I understand if this is a unpassable limitation.

## Additional context
This is the if statements responsible for this behaviour (Line 58 - 69)
https://github.com/jeffvli/feishin/blob/340344b791bbbed7f23ede2fb1d6170c22ebcef7/src/renderer/features/discord-rpc/use-discord-rpc.ts#L58C1-L69C10

This is a Navidrome specific feature

**Comment by iiPythonx** [comment] 2024-03-19 18:22
Part of this limitation was discussed in https://github.com/jeffvli/feishin/pull/515#issuecomment-1950706808, as sending the Navidrome image URL to discord would leak your credentials (as they're sent inside of the url). The main hurdle is still the fact that your Navidrome server would need to be publicly accessible, otherwise Feishin would need to use a service like imgur to act as a middleman.

**Comment by kgarner7** [comment] 2024-04-01 01:46
Closing as duplicate of #341 (the comment from iiPythonx is still correct though).

**Closed as not planned by kgarner7** 2024-04-01 01:46 UTC
Labels: enhancement, frozen-due-to-age
