### ISSUE TITLE
Lyrics loading error

### ISSUE THREAD

**Issue by tianmiao8152** [jeffvli/feishin#507] opened 2024-02-15 07:29 UTC
## Expected Behavior
returned to normal

## Current Behavior
The lyrics are incorrectly interpreted.

## Steps to Reproduce

1.Navidrome server album picture error (issues have been raised to Navidrome)

2.Restart Navidrome Server and uninstall Feishin

3.install Feishin

4.Lyrics Parsing Error

## Possible Solution (Not obligatory)
I think it's [feishin](https://github.com/jeffvli/feishin) parsing the lyrics, because I can use another client[音流](https://aqzscn.cn/archives/stream-music-versions) and the web to display the lyrics properly
Feishin
![image](https://github.com/jeffvli/feishin/assets/83683108/529f1c19-8e0a-406c-9b19-9598118b8cfe)
音流
![image](https://github.com/jeffvli/feishin/assets/83683108/8ea1403d-bcd6-4d9c-b401-1cb93e1766f5)

## Your Environment

-   Application version (e.g. v0.1.0) :0.5.3
-   Operating System and version (e.g. Windows 10) :Windows 10
-   Server and version (e.g. Navidrome v0.48.0) :Navidrome [0.51.0](https://github.com/navidrome/navidrome/releases/tag/v0.51.0) (fd61b29a)
-   Node version (if developing locally) :

**Comment by kgarner7** [comment] 2024-02-15 07:32
Duplicate of https://github.com/jeffvli/feishin/issues/468. Closing as it's fixed in development. Note that when the desktop application (eventually) gets an update, you will need to clear the Feishin cache.

**Closed as completed by kgarner7** 2024-02-15 07:32 UTC
Labels: bug, frozen-due-to-age
