### ISSUE TITLE
Lyrics button goes off screen if lyrics contains long single string (Fullscreen player)

### ISSUE THREAD

**Issue by qstar-inc** [jeffvli/feishin#714] opened 2024-08-23 20:29 UTC
### Expected Behavior

The lyric viewport on the Fullscreen player should be limited to the maximum possible value instead of taking it from the width of the max single string size.

### Current Behavior

![image](https://github.com/user-attachments/assets/c88f96bd-b389-4f34-820a-02228784fb99)

### Steps to Reproduce

1. Play a song with long string in the lyrics attached.
2. Open Fullscreen player.
3. See the lyrics "overflowing" out of the screen/windows/viewport.

### Possible Solution

The div "LyricsContainer-sc-t2si23 HivKC" should have some kind of max width.

### Application version

0.7.3

### Operating System and version

Windows 11 desktop

### Server and Version

Navidrome 0.52.5

**Comment by iiPythonx** [comment] 2024-08-23 20:35
If I'm not mistaken, this would be fixed by https://github.com/jeffvli/feishin/commit/ebebdc1e03b2d0a51067a7e143febca20a7fd635, which hasn't been released yet.

**Comment by kgarner7** [comment] 2024-08-23 20:35
Duplicate of #683, already resolved (try it out on https://feishin.vercel.app)

**Closed as not planned** 2024-08-23 20:35 UTC
Labels: bug, frozen-due-to-age
