### ISSUE TITLE
Group playing for Feishin

### ISSUE THREAD

**Issue by ghost** [jeffvli/feishin#778] opened 2024-10-03 21:38 UTC
### What do you want to be added?

I want Jellyfin's group feature to be added to Feishin.

I do not know how complex of a task is this one, but i'd love it so me and my friends could listen to music together in a spotify like UI.

### Is this a server-specific feature? (e.g. Jellyfin only)

- [X] Yes

**Comment by kgarner7** [comment] 2024-10-04 01:20
Duplicate of #352

**Closed as not planned by kgarner7** 2024-10-04 01:20 UTC
Labels: enhancement, frozen-due-to-age
