### ISSUE TITLE
The queue is empty after restart

### ISSUE THREAD

**Issue by akinhet** [jeffvli/feishin#427] opened 2023-12-30 13:02 UTC
## Expected Behavior

The queue is saved when closing feishin.

## Current Behavior

I have the same issue as https://github.com/jeffvli/feishin/issues/86. Whenever I start feishin the queue is empty.

I tested the output and this is what I got when I closed it normally (closing the window):

```
(node:11102) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at y.quit (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:359741)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523912)
    at App.emit (node:events:526:35)
(Use `feishin --trace-warnings ...` to show where the warning was created)
(node:11102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11102) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at y.quit (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:359741)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523810)
    at App.emit (node:events:514:28)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523948)
    at App.emit (node:events:526:35)
(node:11102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

(This is with --trace-warnings):
```
(node:16011) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at y.quit (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:359741)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523912)
    at App.emit (node:events:526:35)
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:16011) TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at y.quit (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:359741)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523912)
    at App.emit (node:events:526:35)
(node:16011) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at y.quit (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:359741)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523810)
    at App.emit (node:events:514:28)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523948)
    at App.emit (node:events:526:35)
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:16011) TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at y.quit (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:359741)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523810)
    at App.emit (node:events:514:28)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523948)
    at App.emit (node:events:526:35)
```

and this is what I got when I pressed Ctrl+C in the terminal from which I run feishin:

```
(node:15349) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at y.quit (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:359741)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523810)
    at App.emit (node:events:514:28)
(Use `feishin --trace-warnings ...` to show where the warning was created)
(node:15349) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

(again with --trace-warnings):

```
(node:16692) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at y.quit (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:359741)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523810)
    at App.emit (node:events:514:28)
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:16692) TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at y.quit (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:359741)
    at App.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:523810)
    at App.emit (node:events:514:28)
```

## Steps to Reproduce

1. Fill Queue
1. Play a song
1. Exit feishin
1. Start feishin
1. Now queue is empty

## Your Environment

-   Application version (e.g. v0.1.0) : v0.5.3
-   Operating System and version (e.g. Windows 10) : Arch Linux
-   Server and version (e.g. Navidrome v0.48.0) : v0.49.3
-   Node version (if developing locally) : v21.4.0

**Comment by kgarner7** [comment] 2024-01-28 20:38
I'm unfortunately unable to reproduce this, but I do have two sets of changes that should help identify this issue further. Can you try a build off of https://github.com/kgarner7/feishin/tree/try-remove-all-debug and see if that helps?

**Comment by kgarner7** [comment] 2024-02-17 04:52
In the meantime, can you please try https://drive.proton.me/urls/TNKPCJ483C#30VFCpjateVs (either build, this uses my node mpv) to see if it resolves your issue?

**Comment by kgarner7** [comment] 2024-04-11 04:19
Resolved by https://github.com/jeffvli/feishin/commit/9339c0877706bf1b292a23ac4c9c67cd99032843

**Closed as completed by kgarner7** 2024-04-11 04:19 UTC
Labels: bug, frozen-due-to-age
